### PR TITLE
quotes page content in json file

### PR DESCRIPTION
**Pull request by JordanDDisch**

### CODE REVIEW

**Comment by rcaracaus** [comment]
reroll

**Comment by milesthedisch** [comment]
All quote authors should be bold #123

**Comment by milesthedisch** [comment]
All quote authors should be bold #123

**Comment by rcaracaus** [comment]
Why is there no longer 100 quotes?

**Comment by JordanDDisch** [comment]
because there where many quotes that had nothing to do with veganisim

**Pull request merged**
